[15-Jun-2019 15:53:10 Europe/Berlin] Uncaught exception: 'Error' with message 'Call to undefined method Core\View::renderTemplate()''
Stack trace: #0 [internal function]: App\Controllers\Home->indexAction()
#1 C:\xampp\htdocs\Core\Controller.php(55): call_user_func_array(Array, Array)
#2 C:\xampp\htdocs\Core\Router.php(117): Core\Controller->__call('index', Array)
#3 C:\xampp\htdocs\public\index.php(50): Core\Router->dispatch('')
#4 {main}
Thrown in 'C:\xampp\htdocs\App\Controllers\Home.php' on line 30
[15-Jun-2019 15:53:10 Europe/Berlin] PHP Fatal error:  Uncaught Error: Call to undefined method Core\View::renderTemplate() in C:\xampp\htdocs\Core\Error.php:75
Stack trace:
#0 [internal function]: Core\Error::exceptionHandler(Object(Error))
#1 {main}
  thrown in C:\xampp\htdocs\Core\Error.php on line 75
[15-Jun-2019 15:53:10 Europe/Berlin] Uncaught exception: 'Exception' with message 'No route matched.''
Stack trace: #0 C:\xampp\htdocs\public\index.php(50): Core\Router->dispatch('favicon.ico')
#1 {main}
Thrown in 'C:\xampp\htdocs\Core\Router.php' on line 125
[15-Jun-2019 15:53:10 Europe/Berlin] PHP Fatal error:  Uncaught Error: Call to undefined method Core\View::renderTemplate() in C:\xampp\htdocs\Core\Error.php:75
Stack trace:
#0 [internal function]: Core\Error::exceptionHandler(Object(Exception))
#1 {main}
  thrown in C:\xampp\htdocs\Core\Error.php on line 75
[15-Jun-2019 16:24:48 Europe/Berlin] Uncaught exception: 'ErrorException' with message 'include(base.php): failed to open stream: No such file or directory''
Stack trace: #0 C:\xampp\htdocs\App\Views\Home\index.php(1): Core\Error::errorHandler(2, 'include(base.ph...', 'C:\\xampp\\htdocs...', 1, Array)
#1 C:\xampp\htdocs\App\Views\Home\index.php(1): include()
#2 C:\xampp\htdocs\Core\View.php(28): require('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\Core\View.php(44): Core\View::render('Home/index.php', Array)
#4 C:\xampp\htdocs\App\Controllers\Home.php(22): Core\View::renderTemplate('Home/index.php')
#5 [internal function]: App\Controllers\Home->indexAction()
#6 C:\xampp\htdocs\Core\Controller.php(48): call_user_func_array(Array, Array)
#7 C:\xampp\htdocs\Core\Router.php(111): Core\Controller->__call('index', Array)
#8 C:\xampp\htdocs\public\index.php(50): Core\Router->dispatch('')
#9 {main}
Thrown in 'C:\xampp\htdocs\App\Views\Home\index.php' on line 1
[15-Jun-2019 16:25:08 Europe/Berlin] Uncaught exception: 'ErrorException' with message 'include(base.php): failed to open stream: No such file or directory''
Stack trace: #0 C:\xampp\htdocs\App\Views\Home\index.php(1): Core\Error::errorHandler(2, 'include(base.ph...', 'C:\\xampp\\htdocs...', 1, Array)
#1 C:\xampp\htdocs\App\Views\Home\index.php(1): include()
#2 C:\xampp\htdocs\Core\View.php(28): require('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\Core\View.php(44): Core\View::render('Home/index.php', Array)
#4 C:\xampp\htdocs\App\Controllers\Home.php(22): Core\View::renderTemplate('Home/index.php')
#5 [internal function]: App\Controllers\Home->indexAction()
#6 C:\xampp\htdocs\Core\Controller.php(48): call_user_func_array(Array, Array)
#7 C:\xampp\htdocs\Core\Router.php(111): Core\Controller->__call('index', Array)
#8 C:\xampp\htdocs\public\index.php(50): Core\Router->dispatch('')
#9 {main}
Thrown in 'C:\xampp\htdocs\App\Views\Home\index.php' on line 1
[15-Jun-2019 16:25:09 Europe/Berlin] Uncaught exception: 'ErrorException' with message 'include(base.php): failed to open stream: No such file or directory''
Stack trace: #0 C:\xampp\htdocs\App\Views\Home\index.php(1): Core\Error::errorHandler(2, 'include(base.ph...', 'C:\\xampp\\htdocs...', 1, Array)
#1 C:\xampp\htdocs\App\Views\Home\index.php(1): include()
#2 C:\xampp\htdocs\Core\View.php(28): require('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\Core\View.php(44): Core\View::render('Home/index.php', Array)
#4 C:\xampp\htdocs\App\Controllers\Home.php(22): Core\View::renderTemplate('Home/index.php')
#5 [internal function]: App\Controllers\Home->indexAction()
#6 C:\xampp\htdocs\Core\Controller.php(48): call_user_func_array(Array, Array)
#7 C:\xampp\htdocs\Core\Router.php(111): Core\Controller->__call('index', Array)
#8 C:\xampp\htdocs\public\index.php(50): Core\Router->dispatch('')
#9 {main}
Thrown in 'C:\xampp\htdocs\App\Views\Home\index.php' on line 1
[15-Jun-2019 16:25:09 Europe/Berlin] Uncaught exception: 'ErrorException' with message 'include(base.php): failed to open stream: No such file or directory''
Stack trace: #0 C:\xampp\htdocs\App\Views\Home\index.php(1): Core\Error::errorHandler(2, 'include(base.ph...', 'C:\\xampp\\htdocs...', 1, Array)
#1 C:\xampp\htdocs\App\Views\Home\index.php(1): include()
#2 C:\xampp\htdocs\Core\View.php(28): require('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\Core\View.php(44): Core\View::render('Home/index.php', Array)
#4 C:\xampp\htdocs\App\Controllers\Home.php(22): Core\View::renderTemplate('Home/index.php')
#5 [internal function]: App\Controllers\Home->indexAction()
#6 C:\xampp\htdocs\Core\Controller.php(48): call_user_func_array(Array, Array)
#7 C:\xampp\htdocs\Core\Router.php(111): Core\Controller->__call('index', Array)
#8 C:\xampp\htdocs\public\index.php(50): Core\Router->dispatch('')
#9 {main}
Thrown in 'C:\xampp\htdocs\App\Views\Home\index.php' on line 1
[15-Jun-2019 16:25:09 Europe/Berlin] Uncaught exception: 'ErrorException' with message 'include(base.php): failed to open stream: No such file or directory''
Stack trace: #0 C:\xampp\htdocs\App\Views\Home\index.php(1): Core\Error::errorHandler(2, 'include(base.ph...', 'C:\\xampp\\htdocs...', 1, Array)
#1 C:\xampp\htdocs\App\Views\Home\index.php(1): include()
#2 C:\xampp\htdocs\Core\View.php(28): require('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\Core\View.php(44): Core\View::render('Home/index.php', Array)
#4 C:\xampp\htdocs\App\Controllers\Home.php(22): Core\View::renderTemplate('Home/index.php')
#5 [internal function]: App\Controllers\Home->indexAction()
#6 C:\xampp\htdocs\Core\Controller.php(48): call_user_func_array(Array, Array)
#7 C:\xampp\htdocs\Core\Router.php(111): Core\Controller->__call('index', Array)
#8 C:\xampp\htdocs\public\index.php(50): Core\Router->dispatch('')
#9 {main}
Thrown in 'C:\xampp\htdocs\App\Views\Home\index.php' on line 1
[15-Jun-2019 16:25:09 Europe/Berlin] Uncaught exception: 'ErrorException' with message 'include(base.php): failed to open stream: No such file or directory''
Stack trace: #0 C:\xampp\htdocs\App\Views\Home\index.php(1): Core\Error::errorHandler(2, 'include(base.ph...', 'C:\\xampp\\htdocs...', 1, Array)
#1 C:\xampp\htdocs\App\Views\Home\index.php(1): include()
#2 C:\xampp\htdocs\Core\View.php(28): require('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\Core\View.php(44): Core\View::render('Home/index.php', Array)
#4 C:\xampp\htdocs\App\Controllers\Home.php(22): Core\View::renderTemplate('Home/index.php')
#5 [internal function]: App\Controllers\Home->indexAction()
#6 C:\xampp\htdocs\Core\Controller.php(48): call_user_func_array(Array, Array)
#7 C:\xampp\htdocs\Core\Router.php(111): Core\Controller->__call('index', Array)
#8 C:\xampp\htdocs\public\index.php(50): Core\Router->dispatch('')
#9 {main}
Thrown in 'C:\xampp\htdocs\App\Views\Home\index.php' on line 1
[15-Jun-2019 16:25:09 Europe/Berlin] Uncaught exception: 'ErrorException' with message 'include(base.php): failed to open stream: No such file or directory''
Stack trace: #0 C:\xampp\htdocs\App\Views\Home\index.php(1): Core\Error::errorHandler(2, 'include(base.ph...', 'C:\\xampp\\htdocs...', 1, Array)
#1 C:\xampp\htdocs\App\Views\Home\index.php(1): include()
#2 C:\xampp\htdocs\Core\View.php(28): require('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\Core\View.php(44): Core\View::render('Home/index.php', Array)
#4 C:\xampp\htdocs\App\Controllers\Home.php(22): Core\View::renderTemplate('Home/index.php')
#5 [internal function]: App\Controllers\Home->indexAction()
#6 C:\xampp\htdocs\Core\Controller.php(48): call_user_func_array(Array, Array)
#7 C:\xampp\htdocs\Core\Router.php(111): Core\Controller->__call('index', Array)
#8 C:\xampp\htdocs\public\index.php(50): Core\Router->dispatch('')
#9 {main}
Thrown in 'C:\xampp\htdocs\App\Views\Home\index.php' on line 1
[15-Jun-2019 16:25:09 Europe/Berlin] Uncaught exception: 'ErrorException' with message 'include(base.php): failed to open stream: No such file or directory''
Stack trace: #0 C:\xampp\htdocs\App\Views\Home\index.php(1): Core\Error::errorHandler(2, 'include(base.ph...', 'C:\\xampp\\htdocs...', 1, Array)
#1 C:\xampp\htdocs\App\Views\Home\index.php(1): include()
#2 C:\xampp\htdocs\Core\View.php(28): require('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\Core\View.php(44): Core\View::render('Home/index.php', Array)
#4 C:\xampp\htdocs\App\Controllers\Home.php(22): Core\View::renderTemplate('Home/index.php')
#5 [internal function]: App\Controllers\Home->indexAction()
#6 C:\xampp\htdocs\Core\Controller.php(48): call_user_func_array(Array, Array)
#7 C:\xampp\htdocs\Core\Router.php(111): Core\Controller->__call('index', Array)
#8 C:\xampp\htdocs\public\index.php(50): Core\Router->dispatch('')
#9 {main}
Thrown in 'C:\xampp\htdocs\App\Views\Home\index.php' on line 1
[15-Jun-2019 16:25:10 Europe/Berlin] Uncaught exception: 'ErrorException' with message 'include(base.php): failed to open stream: No such file or directory''
Stack trace: #0 C:\xampp\htdocs\App\Views\Home\index.php(1): Core\Error::errorHandler(2, 'include(base.ph...', 'C:\\xampp\\htdocs...', 1, Array)
#1 C:\xampp\htdocs\App\Views\Home\index.php(1): include()
#2 C:\xampp\htdocs\Core\View.php(28): require('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\Core\View.php(44): Core\View::render('Home/index.php', Array)
#4 C:\xampp\htdocs\App\Controllers\Home.php(22): Core\View::renderTemplate('Home/index.php')
#5 [internal function]: App\Controllers\Home->indexAction()
#6 C:\xampp\htdocs\Core\Controller.php(48): call_user_func_array(Array, Array)
#7 C:\xampp\htdocs\Core\Router.php(111): Core\Controller->__call('index', Array)
#8 C:\xampp\htdocs\public\index.php(50): Core\Router->dispatch('')
#9 {main}
Thrown in 'C:\xampp\htdocs\App\Views\Home\index.php' on line 1
[15-Jun-2019 16:26:26 Europe/Berlin] Uncaught exception: 'Error' with message 'Call to undefined function extend()''
Stack trace: #0 C:\xampp\htdocs\Core\View.php(28): require()
#1 C:\xampp\htdocs\Core\View.php(44): Core\View::render('Home/index.php', Array)
#2 C:\xampp\htdocs\App\Controllers\Home.php(22): Core\View::renderTemplate('Home/index.php')
#3 [internal function]: App\Controllers\Home->indexAction()
#4 C:\xampp\htdocs\Core\Controller.php(48): call_user_func_array(Array, Array)
#5 C:\xampp\htdocs\Core\Router.php(111): Core\Controller->__call('index', Array)
#6 C:\xampp\htdocs\public\index.php(50): Core\Router->dispatch('')
#7 {main}
Thrown in 'C:\xampp\htdocs\App\Views\Home\index.php' on line 1
[15-Jun-2019 16:26:50 Europe/Berlin] Uncaught exception: 'Error' with message 'Call to undefined function extend()''
Stack trace: #0 C:\xampp\htdocs\Core\View.php(28): require()
#1 C:\xampp\htdocs\Core\View.php(44): Core\View::render('Home/index.php', Array)
#2 C:\xampp\htdocs\App\Controllers\Home.php(22): Core\View::renderTemplate('Home/index.php')
#3 [internal function]: App\Controllers\Home->indexAction()
#4 C:\xampp\htdocs\Core\Controller.php(48): call_user_func_array(Array, Array)
#5 C:\xampp\htdocs\Core\Router.php(111): Core\Controller->__call('index', Array)
#6 C:\xampp\htdocs\public\index.php(50): Core\Router->dispatch('')
#7 {main}
Thrown in 'C:\xampp\htdocs\App\Views\Home\index.php' on line 1
[15-Jun-2019 16:50:32 Europe/Berlin] Uncaught exception: 'Exception' with message 'No route matched.''
Stack trace: #0 C:\xampp\htdocs\public\index.php(50): Core\Router->dispatch('favicon.ico')
#1 {main}
Thrown in 'C:\xampp\htdocs\Core\Router.php' on line 119
[15-Jun-2019 16:51:29 Europe/Berlin] Uncaught exception: 'Error' with message 'Call to undefined function startblock()''
Stack trace: #0 C:\xampp\htdocs\App\Views\Home\index.php(1): require_once()
#1 C:\xampp\htdocs\Core\View.php(28): require('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\Core\View.php(44): Core\View::render('Home/index.php', Array)
#3 C:\xampp\htdocs\App\Controllers\Home.php(22): Core\View::renderTemplate('Home/index.php')
#4 [internal function]: App\Controllers\Home->indexAction()
#5 C:\xampp\htdocs\Core\Controller.php(48): call_user_func_array(Array, Array)
#6 C:\xampp\htdocs\Core\Router.php(111): Core\Controller->__call('index', Array)
#7 C:\xampp\htdocs\public\index.php(50): Core\Router->dispatch('')
#8 {main}
Thrown in 'C:\xampp\htdocs\App\Views\base.php' on line 58
[15-Jun-2019 16:52:46 Europe/Berlin] Uncaught exception: 'ParseError' with message 'syntax error, unexpected end of file''
Stack trace: #0 C:\xampp\htdocs\Core\View.php(44): Core\View::render('Home/index.php', Array)
#1 C:\xampp\htdocs\App\Controllers\Home.php(22): Core\View::renderTemplate('Home/index.php')
#2 [internal function]: App\Controllers\Home->indexAction()
#3 C:\xampp\htdocs\Core\Controller.php(48): call_user_func_array(Array, Array)
#4 C:\xampp\htdocs\Core\Router.php(111): Core\Controller->__call('index', Array)
#5 C:\xampp\htdocs\public\index.php(50): Core\Router->dispatch('')
#6 {main}
Thrown in 'C:\xampp\htdocs\App\Views\Home\index.php' on line 11
[15-Jun-2019 17:00:39 Europe/Berlin] Uncaught exception: 'Exception' with message 'No route matched.''
Stack trace: #0 C:\xampp\htdocs\public\index.php(50): Core\Router->dispatch('signup/new/test')
#1 {main}
Thrown in 'C:\xampp\htdocs\Core\Router.php' on line 119
[15-Jun-2019 17:00:39 Europe/Berlin] PHP Fatal error:  Uncaught Exception: ../App/Views/404.html not found in C:\xampp\htdocs\Core\View.php:30
Stack trace:
#0 C:\xampp\htdocs\Core\View.php(44): Core\View::render('404.html', Array)
#1 C:\xampp\htdocs\Core\Error.php(67): Core\View::renderTemplate('404.html')
#2 [internal function]: Core\Error::exceptionHandler(Object(Exception))
#3 {main}
  thrown in C:\xampp\htdocs\Core\View.php on line 30
[15-Jun-2019 17:00:43 Europe/Berlin] Uncaught exception: 'Exception' with message 'Method newsAction not found in controller App\Controllers\Signup''
Stack trace: #0 C:\xampp\htdocs\Core\Router.php(111): Core\Controller->__call('news', Array)
#1 C:\xampp\htdocs\public\index.php(50): Core\Router->dispatch('signup/news')
#2 {main}
Thrown in 'C:\xampp\htdocs\Core\Controller.php' on line 52
[15-Jun-2019 17:01:15 Europe/Berlin] Uncaught exception: 'Exception' with message 'Method newsAction not found in controller App\Controllers\Signup''
Stack trace: #0 C:\xampp\htdocs\Core\Router.php(111): Core\Controller->__call('news', Array)
#1 C:\xampp\htdocs\public\index.php(50): Core\Router->dispatch('signup/news')
#2 {main}
Thrown in 'C:\xampp\htdocs\Core\Controller.php' on line 52
[15-Jun-2019 17:01:15 Europe/Berlin] PHP Fatal error:  Uncaught Exception: ../App/Views/500.html not found in C:\xampp\htdocs\Core\View.php:30
Stack trace:
#0 C:\xampp\htdocs\Core\View.php(44): Core\View::render('500.html', Array)
#1 C:\xampp\htdocs\Core\Error.php(67): Core\View::renderTemplate('500.html')
#2 [internal function]: Core\Error::exceptionHandler(Object(Exception))
#3 {main}
  thrown in C:\xampp\htdocs\Core\View.php on line 30
[15-Jun-2019 17:02:23 Europe/Berlin] Uncaught exception: 'Exception' with message 'Method newsAction not found in controller App\Controllers\Signup''
Stack trace: #0 C:\xampp\htdocs\Core\Router.php(111): Core\Controller->__call('news', Array)
#1 C:\xampp\htdocs\public\index.php(50): Core\Router->dispatch('signup/news')
#2 {main}
Thrown in 'C:\xampp\htdocs\Core\Controller.php' on line 52
[15-Jun-2019 17:02:23 Europe/Berlin] PHP Fatal error:  Uncaught ErrorException: Use of undefined constant php - assumed 'php' (this will throw an Error in a future version of PHP) in C:\xampp\htdocs\Core\View.php:25
Stack trace:
#0 C:\xampp\htdocs\Core\View.php(25): Core\Error::errorHandler(2, 'Use of undefine...', 'C:\\xampp\\htdocs...', 25, Array)
#1 C:\xampp\htdocs\Core\View.php(44): Core\View::render('500.html', Array)
#2 C:\xampp\htdocs\Core\Error.php(67): Core\View::renderTemplate('500.html')
#3 [internal function]: Core\Error::exceptionHandler(Object(Exception))
#4 {main}
  thrown in C:\xampp\htdocs\Core\View.php on line 25
[15-Jun-2019 17:02:28 Europe/Berlin] Uncaught exception: 'Exception' with message 'Method newsAction not found in controller App\Controllers\Signup''
Stack trace: #0 C:\xampp\htdocs\Core\Router.php(111): Core\Controller->__call('news', Array)
#1 C:\xampp\htdocs\public\index.php(50): Core\Router->dispatch('signup/news')
#2 {main}
Thrown in 'C:\xampp\htdocs\Core\Controller.php' on line 52
[15-Jun-2019 17:02:28 Europe/Berlin] PHP Fatal error:  Uncaught Exception: ../App/Views/500.html.php not found in C:\xampp\htdocs\Core\View.php:30
Stack trace:
#0 C:\xampp\htdocs\Core\View.php(44): Core\View::render('500.html', Array)
#1 C:\xampp\htdocs\Core\Error.php(67): Core\View::renderTemplate('500.html')
#2 [internal function]: Core\Error::exceptionHandler(Object(Exception))
#3 {main}
  thrown in C:\xampp\htdocs\Core\View.php on line 30
[15-Jun-2019 17:03:24 Europe/Berlin] Uncaught exception: 'Exception' with message 'Method newsAction not found in controller App\Controllers\Signup''
Stack trace: #0 C:\xampp\htdocs\Core\Router.php(111): Core\Controller->__call('news', Array)
#1 C:\xampp\htdocs\public\index.php(50): Core\Router->dispatch('signup/news')
#2 {main}
Thrown in 'C:\xampp\htdocs\Core\Controller.php' on line 52
[15-Jun-2019 17:03:46 Europe/Berlin] Uncaught exception: 'Exception' with message 'No route matched.''
Stack trace: #0 C:\xampp\htdocs\public\index.php(50): Core\Router->dispatch('items')
#1 {main}
Thrown in 'C:\xampp\htdocs\Core\Router.php' on line 119
[15-Jun-2019 17:04:26 Europe/Berlin] Uncaught exception: 'Exception' with message 'No route matched.''
Stack trace: #0 C:\xampp\htdocs\public\index.php(50): Core\Router->dispatch('items')
#1 {main}
Thrown in 'C:\xampp\htdocs\Core\Router.php' on line 119
[15-Jun-2019 17:05:42 Europe/Berlin] Uncaught exception: 'PDOException' with message 'SQLSTATE[HY000] [1045] Access denied for user 'mvcuser'@'localhost' (using password: YES)''
Stack trace: #0 C:\xampp\htdocs\Core\Model.php(26): PDO->__construct('mysql:host=loca...', 'mvcuser', 'secret')
#1 C:\xampp\htdocs\App\Models\User.php(139): Core\Model::getDB()
#2 C:\xampp\htdocs\App\Models\User.php(160): App\Models\User::findByEmail('')
#3 C:\xampp\htdocs\App\Controllers\Login.php(36): App\Models\User::authenticate('', '')
#4 [internal function]: App\Controllers\Login->createAction()
#5 C:\xampp\htdocs\Core\Controller.php(48): call_user_func_array(Array, Array)
#6 C:\xampp\htdocs\Core\Router.php(111): Core\Controller->__call('create', Array)
#7 C:\xampp\htdocs\public\index.php(50): Core\Router->dispatch('login/create')
#8 {main}
Thrown in 'C:\xampp\htdocs\Core\Model.php' on line 26
[15-Jun-2019 17:06:08 Europe/Berlin] Uncaught exception: 'PDOException' with message 'SQLSTATE[HY000] [1045] Access denied for user 'mvcuser'@'localhost' (using password: YES)''
Stack trace: #0 C:\xampp\htdocs\Core\Model.php(26): PDO->__construct('mysql:host=loca...', 'mvcuser', 'secret')
#1 C:\xampp\htdocs\App\Models\User.php(139): Core\Model::getDB()
#2 C:\xampp\htdocs\App\Models\User.php(160): App\Models\User::findByEmail('')
#3 C:\xampp\htdocs\App\Controllers\Login.php(36): App\Models\User::authenticate('', '')
#4 [internal function]: App\Controllers\Login->createAction()
#5 C:\xampp\htdocs\Core\Controller.php(48): call_user_func_array(Array, Array)
#6 C:\xampp\htdocs\Core\Router.php(111): Core\Controller->__call('create', Array)
#7 C:\xampp\htdocs\public\index.php(50): Core\Router->dispatch('login/create')
#8 {main}
Thrown in 'C:\xampp\htdocs\Core\Model.php' on line 26
[15-Jun-2019 17:06:14 Europe/Berlin] Uncaught exception: 'PDOException' with message 'SQLSTATE[HY000] [1045] Access denied for user 'mvcuser'@'localhost' (using password: YES)''
Stack trace: #0 C:\xampp\htdocs\Core\Model.php(26): PDO->__construct('mysql:host=loca...', 'mvcuser', 'secret')
#1 C:\xampp\htdocs\App\Models\User.php(139): Core\Model::getDB()
#2 C:\xampp\htdocs\App\Models\User.php(160): App\Models\User::findByEmail('rick.wubs@gmail...')
#3 C:\xampp\htdocs\App\Controllers\Login.php(36): App\Models\User::authenticate('rick.wubs@gmail...', 'secret1')
#4 [internal function]: App\Controllers\Login->createAction()
#5 C:\xampp\htdocs\Core\Controller.php(48): call_user_func_array(Array, Array)
#6 C:\xampp\htdocs\Core\Router.php(111): Core\Controller->__call('create', Array)
#7 C:\xampp\htdocs\public\index.php(50): Core\Router->dispatch('login/create')
#8 {main}
Thrown in 'C:\xampp\htdocs\Core\Model.php' on line 26
[15-Jun-2019 17:07:35 Europe/Berlin] Uncaught exception: 'PDOException' with message 'SQLSTATE[HY000] [1045] Access denied for user 'mvcuser'@'localhost' (using password: YES)''
Stack trace: #0 C:\xampp\htdocs\Core\Model.php(26): PDO->__construct('mysql:host=loca...', 'mvcuser', 'secret')
#1 C:\xampp\htdocs\App\Models\User.php(139): Core\Model::getDB()
#2 C:\xampp\htdocs\App\Models\User.php(160): App\Models\User::findByEmail('rick.wubs@gmail...')
#3 C:\xampp\htdocs\App\Controllers\Login.php(36): App\Models\User::authenticate('rick.wubs@gmail...', 'secret1')
#4 [internal function]: App\Controllers\Login->createAction()
#5 C:\xampp\htdocs\Core\Controller.php(48): call_user_func_array(Array, Array)
#6 C:\xampp\htdocs\Core\Router.php(111): Core\Controller->__call('create', Array)
#7 C:\xampp\htdocs\public\index.php(50): Core\Router->dispatch('login/create')
#8 {main}
Thrown in 'C:\xampp\htdocs\Core\Model.php' on line 26
[15-Jun-2019 17:07:39 Europe/Berlin] Uncaught exception: 'Exception' with message 'No route matched.''
Stack trace: #0 C:\xampp\htdocs\public\index.php(50): Core\Router->dispatch('App/Controllers...')
#1 {main}
Thrown in 'C:\xampp\htdocs\Core\Router.php' on line 119
[15-Jun-2019 17:08:53 Europe/Berlin] Uncaught exception: 'PDOException' with message 'SQLSTATE[HY000] [1045] Access denied for user 'mvcuser'@'localhost' (using password: YES)''
Stack trace: #0 C:\xampp\htdocs\Core\Model.php(26): PDO->__construct('mysql:host=loca...', 'mvcuser', 'secret')
#1 C:\xampp\htdocs\App\Models\User.php(139): Core\Model::getDB()
#2 C:\xampp\htdocs\App\Models\User.php(160): App\Models\User::findByEmail('rick.wubs@gmail...')
#3 C:\xampp\htdocs\App\Controllers\Login.php(36): App\Models\User::authenticate('rick.wubs@gmail...', 'secret1')
#4 [internal function]: App\Controllers\Login->createAction()
#5 C:\xampp\htdocs\Core\Controller.php(48): call_user_func_array(Array, Array)
#6 C:\xampp\htdocs\Core\Router.php(111): Core\Controller->__call('create', Array)
#7 C:\xampp\htdocs\public\index.php(50): Core\Router->dispatch('login/create')
#8 {main}
Thrown in 'C:\xampp\htdocs\Core\Model.php' on line 26
[15-Jun-2019 17:09:39 Europe/Berlin] Uncaught exception: 'Exception' with message '../App/Views/Signup/new.php not found''
Stack trace: #0 C:\xampp\htdocs\Core\View.php(44): Core\View::render('Signup/new.php', Array)
#1 C:\xampp\htdocs\App\Controllers\Signup.php(23): Core\View::renderTemplate('Signup/new.php')
#2 [internal function]: App\Controllers\Signup->newAction()
#3 C:\xampp\htdocs\Core\Controller.php(48): call_user_func_array(Array, Array)
#4 C:\xampp\htdocs\Core\Router.php(111): Core\Controller->__call('new', Array)
#5 C:\xampp\htdocs\public\index.php(50): Core\Router->dispatch('signup')
#6 {main}
Thrown in 'C:\xampp\htdocs\Core\View.php' on line 30
